install:
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - SET PATH=C:\Qt\5.5\msvc2013\bin;%PATH%
  - choco install -y jom
  - SET IFW_PATH=C:\Qt\QtIFW2.0.1

build_script:
  - SET REPO_DIR=%CD%
  - SET INSTALL_ROOT=%REPO_DIR%\install
  - SET INSTALL_EDITION=-rusty
  - cd %REPO_DIR%\qt-creator
  - qmake CONFIG+=release "QTC_PREFIX=/rusty-creator-3.5.0"
  - jom
  - cd %REPO_DIR%\plugin
  - qmake
  - jom
  - cd %REPO_DIR%\qt-creator  
  - jom docs
  - jom install
  - jom install_docs
  - jom deployqt
  - jom deployartifacts
  - jom bindist_installer
  - jom installer

test: off

artifacts:
  - path: qt-creator\qt-creator-windows-rusty-3.5.0.exe
