#############################################################################
# Makefile for building: libRust_debug.dylib
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  plugin/rust.pro
# Template: lib
# Command: /Users/admin/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile plugin/rust.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DRUST_LIBRARY -DWITH_TESTS -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_QML_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator"'
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -fvisibility=hidden -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC $(DEFINES)
INCPATH       = -Iqt-creator-build/src -Iqt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -Iqt-creator/src/plugins -I. -I../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtTest.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I.moc/debug-shared -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/admin/Qt/5.5/clang_64/lib
QMAKE         = /Users/admin/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rust_debug1.0.0
DISTDIR = /Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/.obj/debug-shared/Rust_debug1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-rpath,@loader_path/../,-rpath,@executable_path/../ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -single_module -dynamiclib -Wl,-install_name,@rpath/PlugIns/libRust_debug.dylib
LIBS          = $(SUBLIBS) -F/Users/admin/Qt/5.5/clang_64/lib -L../qt-creator-build/bin/Qt\ Creator.app/Contents/Frameworks -L../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns -lCore_debug -lProjectExplorer_debug -lTextEditor_debug -lQtcSsh_debug -lAggregation_debug -lExtensionSystem_debug -lUtils_debug -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtTest -framework Security -framework ApplicationServices -framework Foundation -framework QtConcurrent -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = .obj/debug-shared/

####### Files

SOURCES       = plugin/rustplugin.cpp \
		plugin/cargoprojectmanager.cpp \
		plugin/cargoproject.cpp \
		plugin/cargoprojectnode.cpp \
		plugin/cargoprojectfile.cpp \
		plugin/rusttoolchainfactory.cpp \
		plugin/rusttoolchain.cpp \
		plugin/rustoutputparser.cpp \
		plugin/rusttoolchainconfigwidget.cpp .rcc/qrc_Rust.cpp \
		.moc/debug-shared/moc_rustplugin.cpp \
		.moc/debug-shared/moc_cargoprojectmanager.cpp \
		.moc/debug-shared/moc_cargoproject.cpp \
		.moc/debug-shared/moc_cargoprojectnode.cpp \
		.moc/debug-shared/moc_cargoprojectfile.cpp \
		.moc/debug-shared/moc_rusttoolchainconfigwidget.cpp
OBJECTS       = .obj/debug-shared/rustplugin.o \
		.obj/debug-shared/cargoprojectmanager.o \
		.obj/debug-shared/cargoproject.o \
		.obj/debug-shared/cargoprojectnode.o \
		.obj/debug-shared/cargoprojectfile.o \
		.obj/debug-shared/rusttoolchainfactory.o \
		.obj/debug-shared/rusttoolchain.o \
		.obj/debug-shared/rustoutputparser.o \
		.obj/debug-shared/rusttoolchainconfigwidget.o \
		.obj/debug-shared/qrc_Rust.o \
		.obj/debug-shared/moc_rustplugin.o \
		.obj/debug-shared/moc_cargoprojectmanager.o \
		.obj/debug-shared/moc_cargoproject.o \
		.obj/debug-shared/moc_cargoprojectnode.o \
		.obj/debug-shared/moc_cargoprojectfile.o \
		.obj/debug-shared/moc_rusttoolchainconfigwidget.o
DIST          = plugin/Rust.json.in \
		plugin/mimetypes.xml \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		plugin/qt-creator/src/plugins/coreplugin/coreplugin_dependencies.pri \
		plugin/qt-creator/src/plugins/projectexplorer/projectexplorer_dependencies.pri \
		plugin/qt-creator/src/plugins/texteditor/texteditor_dependencies.pri \
		plugin/qt-creator/src/libs/aggregation/aggregation_dependencies.pri \
		plugin/qt-creator/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		plugin/qt-creator/src/libs/utils/utils_dependencies.pri \
		plugin/qt-creator/src/libs/ssh/ssh_dependencies.pri \
		plugin/qt-creator/qtcreator.pri \
		plugin/qt-creator/src/rpath.pri \
		plugin/qt-creator/src/qtcreatorplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/hide_symbols.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/xctest.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testlib_defines.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		plugin/plugin/rust.pro plugin/rustplugin.h \
		plugin/rust_global.h \
		plugin/rustconstants.h \
		plugin/cargoprojectmanager.h \
		plugin/cargoproject.h \
		plugin/cargoprojectnode.h \
		plugin/cargoprojectfile.h \
		plugin/rusttoolchainfactory.h \
		plugin/rusttoolchain.h \
		plugin/rustoutputparser.h \
		plugin/rusttoolchainconfigwidget.h plugin/rustplugin.cpp \
		plugin/cargoprojectmanager.cpp \
		plugin/cargoproject.cpp \
		plugin/cargoprojectnode.cpp \
		plugin/cargoprojectfile.cpp \
		plugin/rusttoolchainfactory.cpp \
		plugin/rusttoolchain.cpp \
		plugin/rustoutputparser.cpp \
		plugin/rusttoolchainconfigwidget.cpp
QMAKE_TARGET  = Rust_debug
DESTDIR       = ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/#avoid trailing-slash linebreak
TARGET        = libRust_debug.dylib
TARGETD       = libRust_debug.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-fvisibility=hidden \
		-fvisibility-inlines-hidden \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/ || mkdir -p ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/ 



Makefile: plugin/rust.pro ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		qt-creator/src/plugins/coreplugin/coreplugin_dependencies.pri \
		qt-creator/src/plugins/projectexplorer/projectexplorer_dependencies.pri \
		qt-creator/src/plugins/texteditor/texteditor_dependencies.pri \
		qt-creator/src/libs/aggregation/aggregation_dependencies.pri \
		qt-creator/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		qt-creator/src/libs/utils/utils_dependencies.pri \
		qt-creator/src/libs/ssh/ssh_dependencies.pri \
		qt-creator/qtcreator.pri \
		qt-creator/src/rpath.pri \
		qt-creator/src/qtcreatorplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/hide_symbols.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/xctest.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testlib_defines.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		plugin/rust.pro \
		plugin/Rust.json.in \
		plugin/Rust.qrc \
		/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/QtTest.prl \
		/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl \
		/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile plugin/rust.pro
../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
qt-creator/src/plugins/coreplugin/coreplugin_dependencies.pri:
qt-creator/src/plugins/projectexplorer/projectexplorer_dependencies.pri:
qt-creator/src/plugins/texteditor/texteditor_dependencies.pri:
qt-creator/src/libs/aggregation/aggregation_dependencies.pri:
qt-creator/src/libs/extensionsystem/extensionsystem_dependencies.pri:
qt-creator/src/libs/utils/utils_dependencies.pri:
qt-creator/src/libs/ssh/ssh_dependencies.pri:
qt-creator/qtcreator.pri:
qt-creator/src/rpath.pri:
qt-creator/src/qtcreatorplugin.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/hide_symbols.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/xctest.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/testlib_defines.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
plugin/rust.pro:
plugin/Rust.json.in:
plugin/Rust.qrc:
/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/QtTest.prl:
/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile plugin/rust.pro

qmake_all: FORCE


all: Makefile ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents plugin/Rust.qrc $(DISTDIR)/
	$(COPY_FILE) --parents plugin/rustplugin.h plugin/rust_global.h plugin/rustconstants.h plugin/cargoprojectmanager.h plugin/cargoproject.h plugin/cargoprojectnode.h plugin/cargoprojectfile.h plugin/rusttoolchainfactory.h plugin/rusttoolchain.h plugin/rustoutputparser.h plugin/rusttoolchainconfigwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents plugin/rustplugin.cpp plugin/cargoprojectmanager.cpp plugin/cargoproject.cpp plugin/cargoprojectnode.cpp plugin/cargoprojectfile.cpp plugin/rusttoolchainfactory.cpp plugin/rusttoolchain.cpp plugin/rustoutputparser.cpp plugin/rusttoolchainconfigwidget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../qt-creator-build/bin/Qt\ Creator.app/Contents/PlugIns/$(TARGET) 
	-$(DEL_FILE) .qmake.stash /Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/Rust.json
	-$(DEL_FILE) Makefile


####### Sub-libraries

highlights:
	cp -f generic-highlighter/*.xml ../qt-creator-build/bin/Qt Creator.app/Contents/PlugIns/../../../share/qtcreator/generic-highlighter

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: .rcc/qrc_Rust.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_Rust.cpp
.rcc/qrc_Rust.cpp: plugin/Rust.qrc \
		plugin/mimetypes.xml
	/Users/admin/Qt/5.5/clang_64/bin/rcc -name Rust plugin/Rust.qrc -o .rcc/qrc_Rust.cpp

compiler_moc_header_make_all: .moc/debug-shared/moc_rustplugin.cpp .moc/debug-shared/moc_cargoprojectmanager.cpp .moc/debug-shared/moc_cargoproject.cpp .moc/debug-shared/moc_cargoprojectnode.cpp .moc/debug-shared/moc_cargoprojectfile.cpp .moc/debug-shared/moc_rusttoolchainconfigwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/debug-shared/moc_rustplugin.cpp .moc/debug-shared/moc_cargoprojectmanager.cpp .moc/debug-shared/moc_cargoproject.cpp .moc/debug-shared/moc_cargoprojectnode.cpp .moc/debug-shared/moc_cargoprojectfile.cpp .moc/debug-shared/moc_rusttoolchainconfigwidget.cpp
.moc/debug-shared/moc_rustplugin.cpp: plugin/rust_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/libs/extensionsystem/iplugin.h \
		qt-creator/src/libs/extensionsystem/extensionsystem_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QLoggingCategory \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QtPlugin \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		plugin/rustplugin.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/rustplugin.h -o .moc/debug-shared/moc_rustplugin.cpp

.moc/debug-shared/moc_cargoprojectmanager.cpp: qt-creator/src/plugins/projectexplorer/iprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		plugin/cargoprojectmanager.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/cargoprojectmanager.h -o .moc/debug-shared/moc_cargoprojectmanager.cpp

.moc/debug-shared/moc_cargoproject.cpp: ../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QScopedPointer \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		qt-creator/src/plugins/projectexplorer/project.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileSystemModel \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		plugin/cargoproject.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/cargoproject.h -o .moc/debug-shared/moc_cargoproject.cpp

.moc/debug-shared/moc_cargoprojectnode.cpp: qt-creator/src/plugins/projectexplorer/projectnodes.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		plugin/cargoprojectnode.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/cargoprojectnode.h -o .moc/debug-shared/moc_cargoprojectnode.cpp

.moc/debug-shared/moc_cargoprojectfile.cpp: qt-creator/src/plugins/coreplugin/idocument.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		plugin/cargoprojectfile.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/cargoprojectfile.h -o .moc/debug-shared/moc_cargoprojectfile.cpp

.moc/debug-shared/moc_rusttoolchainconfigwidget.cpp: qt-creator/src/plugins/projectexplorer/toolchainconfigwidget.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QScrollArea \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		plugin/rusttoolchainconfigwidget.h
	/Users/admin/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/admin/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/plugin -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator-build/src -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/libs -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/tools -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator/qt-creator/src/plugins -I/Users/admin/Documents/Workspaces/QTWorkspace/rustycreator -I/Users/admin/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtTest.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/admin/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt/5.5/clang_64/lib plugin/rusttoolchainconfigwidget.h -o .moc/debug-shared/moc_rusttoolchainconfigwidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

.obj/debug-shared/rustplugin.o: plugin/rustplugin.cpp plugin/rustplugin.h \
		plugin/rust_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/libs/extensionsystem/iplugin.h \
		qt-creator/src/libs/extensionsystem/extensionsystem_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QLoggingCategory \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QtPlugin \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		plugin/rustconstants.h \
		qt-creator/src/libs/utils/mimetypes/mimedatabase.h \
		qt-creator/src/libs/utils/mimetypes/mimetype.h \
		qt-creator/src/libs/utils/utils_global.h \
		qt-creator/src/libs/utils/mimetypes/mimemagicrule_p.h \
		plugin/cargoprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/iprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		plugin/rusttoolchainfactory.h \
		qt-creator/src/plugins/projectexplorer/toolchain.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/rustplugin.o plugin/rustplugin.cpp

.obj/debug-shared/cargoprojectmanager.o: plugin/cargoprojectmanager.cpp plugin/cargoprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/iprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		plugin/cargoproject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QScopedPointer \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		qt-creator/src/plugins/projectexplorer/project.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileSystemModel \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/cargoprojectmanager.o plugin/cargoprojectmanager.cpp

.obj/debug-shared/cargoproject.o: plugin/cargoproject.cpp plugin/cargoproject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QScopedPointer \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		qt-creator/src/plugins/projectexplorer/project.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileSystemModel \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		plugin/cargoprojectnode.h \
		qt-creator/src/plugins/projectexplorer/projectnodes.h \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		plugin/cargoprojectmanager.h \
		qt-creator/src/plugins/projectexplorer/iprojectmanager.h \
		plugin/cargoprojectfile.h \
		qt-creator/src/plugins/coreplugin/idocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/cargoproject.o plugin/cargoproject.cpp

.obj/debug-shared/cargoprojectnode.o: plugin/cargoprojectnode.cpp plugin/cargoprojectnode.h \
		qt-creator/src/plugins/projectexplorer/projectnodes.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileSystemWatcher \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfilesystemwatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/cargoprojectnode.o plugin/cargoprojectnode.cpp

.obj/debug-shared/cargoprojectfile.o: plugin/cargoprojectfile.cpp plugin/cargoprojectfile.h \
		qt-creator/src/plugins/coreplugin/idocument.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		qt-creator/src/libs/utils/fileutils.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/cargoprojectfile.o plugin/cargoprojectfile.cpp

.obj/debug-shared/rusttoolchainfactory.o: plugin/rusttoolchainfactory.cpp plugin/rusttoolchainfactory.h \
		qt-creator/src/plugins/projectexplorer/toolchain.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		plugin/rusttoolchain.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/rusttoolchainfactory.o plugin/rusttoolchainfactory.cpp

.obj/debug-shared/rusttoolchain.o: plugin/rusttoolchain.cpp plugin/rusttoolchain.h \
		qt-creator/src/plugins/projectexplorer/toolchain.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		plugin/rustoutputparser.h \
		qt-creator/src/plugins/projectexplorer/ioutputparser.h \
		qt-creator/src/plugins/projectexplorer/buildstep.h \
		qt-creator/src/plugins/projectexplorer/projectconfiguration.h \
		qt-creator/src/libs/utils/macroexpander.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFutureInterface \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		plugin/rusttoolchainconfigwidget.h \
		qt-creator/src/plugins/projectexplorer/toolchainconfigwidget.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QScrollArea \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		qt-creator/src/plugins/projectexplorer/abi.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QHash \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qhash.h \
		qt-creator/src/plugins/projectexplorer/headerpath.h \
		qt-creator/src/libs/utils/fileutils.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QXmlStreamWriter \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		qt-creator/src/libs/utils/environment.h \
		qt-creator/src/libs/utils/hostosinfo.h \
		qt-creator/src/libs/utils/osspecificaspects.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/rusttoolchain.o plugin/rusttoolchain.cpp

.obj/debug-shared/rustoutputparser.o: plugin/rustoutputparser.cpp plugin/rustoutputparser.h \
		qt-creator/src/plugins/projectexplorer/ioutputparser.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		qt-creator/src/plugins/projectexplorer/buildstep.h \
		qt-creator/src/plugins/projectexplorer/projectconfiguration.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		qt-creator/src/libs/utils/macroexpander.h \
		qt-creator/src/libs/utils/utils_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFutureInterface \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/rustoutputparser.o plugin/rustoutputparser.cpp

.obj/debug-shared/rusttoolchainconfigwidget.o: plugin/rusttoolchainconfigwidget.cpp plugin/rusttoolchainconfigwidget.h \
		qt-creator/src/plugins/projectexplorer/toolchainconfigwidget.h \
		qt-creator/src/plugins/projectexplorer/projectexplorer_export.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QScrollArea \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		plugin/rusttoolchain.h \
		qt-creator/src/plugins/projectexplorer/toolchain.h \
		qt-creator/src/plugins/coreplugin/id.h \
		qt-creator/src/plugins/coreplugin/core_global.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QFormLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/rusttoolchainconfigwidget.o plugin/rusttoolchainconfigwidget.cpp

.obj/debug-shared/qrc_Rust.o: .rcc/qrc_Rust.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/qrc_Rust.o .rcc/qrc_Rust.cpp

.obj/debug-shared/moc_rustplugin.o: .moc/debug-shared/moc_rustplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_rustplugin.o .moc/debug-shared/moc_rustplugin.cpp

.obj/debug-shared/moc_cargoprojectmanager.o: .moc/debug-shared/moc_cargoprojectmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_cargoprojectmanager.o .moc/debug-shared/moc_cargoprojectmanager.cpp

.obj/debug-shared/moc_cargoproject.o: .moc/debug-shared/moc_cargoproject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_cargoproject.o .moc/debug-shared/moc_cargoproject.cpp

.obj/debug-shared/moc_cargoprojectnode.o: .moc/debug-shared/moc_cargoprojectnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_cargoprojectnode.o .moc/debug-shared/moc_cargoprojectnode.cpp

.obj/debug-shared/moc_cargoprojectfile.o: .moc/debug-shared/moc_cargoprojectfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_cargoprojectfile.o .moc/debug-shared/moc_cargoprojectfile.cpp

.obj/debug-shared/moc_rusttoolchainconfigwidget.o: .moc/debug-shared/moc_rusttoolchainconfigwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_rusttoolchainconfigwidget.o .moc/debug-shared/moc_rusttoolchainconfigwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

