#ifndef BOUILLABAISSE_GLOBAL_H
#define BOUILLABAISSE_GLOBAL_H

#include <QtGlobal>

#if defined(BOUILLABAISSE_LIBRARY)
#  define BOUILLABAISSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOUILLABAISSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOUILLABAISSE_GLOBAL_H

